title: <p align="center"> Megan Smith </p> 
logo: "/images/LinkedIN 14.png?raw=true" 
description: > 
  <p align="center">
  Expert Data Analyst
  </p>
  <p align="center"> 
  Tableau │ SQL │ Excel │ Python │ R
  </p>
  <br>
  <p align="center"><a href="https://www.linkedin.com/in/megansmithmath/"><img src="images/linkedin_icon30.png?raw=true"/>&nbsp;&nbsp;&nbsp;&nbsp; <a href="https://public.tableau.com/app/profile/megansmithmath/"><img src="images/tableau_icon30.png?raw=true"/>&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/megansmithmath/"><img src="images/GitHub_icon30.png?raw=true"/></p>
  <p align="center"><a href="https://megansmithmath.github.io/"><img src="images/Home Button.png?raw=true"/>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
