title: <p align="center"> Megan Smith </p> # your name (or website title) here
logo: "/images/LinkedIn Square (3).png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  Data-Driven Educator
  </p>
  <p align="center"> 
  Data Analyst │ Excel │ Tableau │ SQL 
  </p>
  <br>
|:<a href="https://www.linkedin.com/in/megansmithmath/"><img src="images/linkedin_icon30.png?raw=true"/>:|:<a href="https://public.tableau.com/app/profile/megansmithmath/"><img src="images/tableau_icon30.png?raw=true"/>:|:<img src="images/GitHub_icon30.png?raw=true"/>:|
|:<a href="https://www.linkedin.com/in/megansmithmath/">LinkedIn</a>:|:<a href="https://public.tableau.com/app/profile/megansmithmath/">Tableau Public</a> </p>:|:<a href="https://github.com/megansmithmath/">GitHub</a>:|
  <p align="center"><a href="https://www.linkedin.com/in/megansmithmath/"><img src="images/linkedin_icon30.png?raw=true"/>&nbsp;&nbsp; <a href="https://www.linkedin.com/in/megansmithmath/">LinkedIn</a></p> 
  <p align="center"><a href="https://public.tableau.com/app/profile/megansmithmath/"><img src="images/tableau_icon30.png?raw=true"/>&nbsp;&nbsp; <a href="https://public.tableau.com/app/profile/megansmithmath/">Tableau</a></p> 
  <p align="center"><a href="https://github.com/megansmithmath/"><img src="images/GitHub_icon30.png?raw=true"/>&nbsp;&nbsp; <a href="https://github.com/megansmithmath/">GitHub</a></p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
