title: <p align="center"> M E G A N   S M I T H </p> # your name (or website title) here
<h1 align="center"> M E G A N   S M I T H </h1>
logo: "/images/LinkedIn Square (3).png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  Data-Driven Educator
  </p>
  <p align="center"> 
  Data Analyst │ Excel │ Tableau │ SQL 
  </p>
  <br><br>
  <a href="https://www.linkedin.com/in/megansmithmath/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
